[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "nvim"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
just = "*"
yq = "*"
jq = "*"
python = "*"
neovim = "*"
pixi-kernel = "*"

[pypi-dependencies]
neopyter = "*"

[feature.molten.dependencies]
plotly = "*"
nbformat = "*"
cairosvg = "*"
pyperclip = "*"
jupyterlab = "*"
orjson = "*"
simplejson = "*"

[feature.molten.pypi-dependencies]
kaleido = "*"
pnglatex = "*"

[activation.env]
JUPYTER_TOKEN = "123"

[environments]
molten = { features = ["molten"], solve-group = "default" }
